platform :ios, '8.0'

target 'IMBaseOnXMPP' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for 知乎日报

pod 'XMPPFramework', '~> 3.7.0'

end
